# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - SGCarparks

on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: windows-latest
    environment: Testing
    strategy:
      matrix:
        node-version: [16.x , 18.x]
      max-parallel: 1  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: 
          ref: 'master'
        
      - name: Install server npm packages
        uses: npm install
        with:
          working-directory: ./server

      - name: Install client npm packages
        uses: npm install
        with:
          working-directory: ./

      - name: Start server in the background
        env: 
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
        run: (cd ./server && echo "ATLAS_URI=$ATLAS_URI" > config.env  && npm start &)

      - name: Start React app in the background
        run: (cd ../ && npm start &)
